/*
  Database structure
*/

DROP TABLE IF EXISTS Activities;
CREATE TABLE Activities ( 
ActivityID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Description VARCHAR(200) NOT NULL,
Rate DECIMAL(10,2) NOT NULL
);

DROP TABLE IF EXISTS Status;
CREATE TABLE Status (
Status TINYINT NOT NULL PRIMARY KEY,
Name VARCHAR(20),
Description VARCHAR(200)
);


